# Generated by Django 3.1.8 on 2021-06-01 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Author's first name", max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(help_text="Author's last name", max_length=255, verbose_name='last name')),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth', null=True, verbose_name='date of birth')),
                ('date_of_death', models.DateField(blank=True, help_text='Date of death', null=True, verbose_name='date of death')),
            ],
            options={
                'db_table': 'authors',
                'ordering': ['date_of_birth'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Book Genre', max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'db_table': 'genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Languages. eg: English', max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'db_table': 'languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Book title', max_length=255, verbose_name='title')),
                ('summary', models.TextField(help_text='Book summary', verbose_name='summary')),
                ('isbn', models.CharField(help_text='ISBN', max_length=13, unique=True, verbose_name='isbn')),
                ('price', models.IntegerField()),
                ('published_date', models.DateField(blank=True, help_text='Date of publication', null=True, verbose_name='publication date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='apps.author')),
                ('genre', models.ManyToManyField(help_text='Genre', to='apps.Genre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='language', to='apps.language')),
            ],
            options={
                'db_table': 'books',
                'ordering': ['title'],
            },
        ),
    ]
