# Generated by Django 3.1.8 on 2021-06-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20210618_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='ISBN', max_length=13, unique=True, verbose_name='isbn'),
        ),
    ]
